name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make test
      - uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs 
