name: C/C++ CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: make
        uses: actions/checkout@v2
          - run: make

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Running tests
        uses: actions/checkout@v2
          - run: make test

      - name: Uploading logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs 
